[application]
name = "Tailwind CSS + Dioxus"
default_platform = "web"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "dioxus | ⛺"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[web.resource]
style = [
    "./assets/main.scss",
    "https://unpkg.com/tailwindcss@2.2/dist/tailwind.min.css",
    "https://unpkg.com/daisyui@4.12.23/dist/full.css",
#    "https://unpkg.com/katex@0.16.0/dist/katex.min.css"
]

[web.resource.dev]
style = []